const NAME_ACTION = {
  SHOW_LOADING: 'SHOW_LOADING',
  HIDE_LOADING: 'HIDE_LOADING',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  GET_TOKEN: 'GET_TOKEN',
  GET_INFOR_USER: 'GET_INFOR_USER',
  GET_LIST_EVENT: 'GET_LIST_EVENT',
  GET_EVENT_DETAIL: 'GET_EVENT_DETAIL',
  GET_LIST_EVENT_JOINED: 'GET_LIST_EVENT_JOINED',
  GET_EVENT_JOINED_DETAIL: 'GET_EVENT_JOINED_DETAIL',
  GET_LIST_RANK: 'GET_LIST_RANK',
  GET_STATISTICAL: 'GET_STATISTICAL',
  HANDLE_RANK: 'HANDLE_RANK',
  HANDLE_CHART: 'HANDLE_CHART',
};

export default NAME_ACTION;
